# Generated by Django 4.1.3 on 2022-12-19 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_blogcategory_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogcategory',
            name='image',
        ),
    ]
